### ISSUE TITLE
Build fails because of pushplugin  with  cordova android@4.0.0

### ISSUE THREAD

**Issue by amsimaganti** [phonegap-build/PushPlugin#537]
After migrating my cordova version to 5 build fails with bellow error 
:compileDebugJavaNote: E:\myapp\platforms\android\src\com\plugin\gcm\PushPlug
in.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:preDexDebug
:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/acce
ssibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionI
mpl;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:45
4)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)

 FAILED

BUILD FAILED
Help me out

**Comment by tvonbomhard** [comment]
1+  Same problem :-(

**Comment by mladenp** [comment]
I also use Cordova Android@4.0 but my error is: "cordova.exec is not a function"
Can it be that this push notification is not tested with latest version?

**Comment by imsingh** [comment]
1+ Same problem. But my case is little wired. 

It builds without pushwoosh cordova plugin. But When I install pushwoosh plugin. It fails to build.

**Comment by kaansoral** [comment]
This is a clash with the facebook plugin

Since they are both not updated, an android resource is imported twice and causes this issue

I guess, in 3-4 months, the issue might be solved, considering the slow pace of both plugins

**Comment by kaansoral** [comment]
It seems the pushplugins use android-support v13 in general and the modified v4 of the facebook sdk conflicts with it, so the issue should probably be solved on that side

**Comment by alpjor** [comment]
Issue was fixed here:
https://github.com/Wizcorp/phonegap-facebook-plugin/pull/1032
